---


#network_ports:
#  - switches:
#      - s1-leaf2
#    switch_ports: # Ex Ethernet1-48 or Ethernet2-3/1-48
#      - Ethernet4
#    enabled: false
#    description: Leaf2_Access_eth4
#    mode: access
#    vlans: "2300"
#    profile: int_access_host

network_ports:
  - switches:
      - s1-leaf2
    switch_ports:
      - Ethernet4
    enabled: true
    mtu: 9000
    profile: int_routed_host
    structured_config:
      ip_address: 10.192.195.21/24
      vrf: Tenant_A_OP_Zone
      description: Routed_Interface_4 int_routed_host
      mtu: 
#      type: routed




# custom_structured_configuration_ethernet_interfaces:
# - name: Ethernet4
#   ip_address: 10.192.195.21/24
#   shutdown: true
#   vrf: Tenant_A_OP_Zone
#   type: routed
#   mtu: 9000
#   description: "Routed_Interface_4"