---


#network_ports:
#  - switches:
#      - s1-leaf[2]
#    switch_ports: # Ex Ethernet1-48 or Ethernet2-3/1-48
#      - Ethernet4
#    description: Leaf2_Access_eth4
#    mode: access
#    vlans: "2300"



 custom_structured_configuration_ethernet_interfaces:
 - name: Ethernet4
   ip_address: 10.192.195.21/24
   shutdown: false
   vrf: Tenant_A_OP_Zone
   type: routed
   mtu: 9000
   description: "Routed_Interface_4"